using System.ComponentModel;

namespace Core.Enums
{
    public enum StateEnum
    {
        [Description("Alabama")] Al,
        [Description("Alaska")] Ak,
        [Description("Arkansas")] Ar,
        [Description("Arizona")] Az,
        [Description("California")] Ca,
        [Description("Colorado")] Co,
        [Description("Connecticut")] Ct,
        [Description("D.C.")] Dc,
        [Description("Delaware")] De,
        [Description("Florida")] Fl,
        [Description("Georgia")] Ga,
        [Description("Hawaii")] Hi,
        [Description("Iowa")] Ia,
        [Description("Idaho")] Id,
        [Description("Illinois")] Il,
        [Description("Indiana")] In,
        [Description("Kansas")] Ks,
        [Description("Kentucky")] Ky,
        [Description("Louisiana")] La,
        [Description("Massachusetts")] Ma,
        [Description("Maryland")] Md,
        [Description("Maine")] Me,
        [Description("Michigan")] Mi,
        [Description("Minnesota")] Mn,
        [Description("Missouri")] Mo,
        [Description("Mississippi")] Ms,
        [Description("Montana")] Mt,
        [Description("North Carolina")] Nc,
        [Description("North Dakota")] Nd,
        [Description("Nebraska")] Ne,
        [Description("New Hampshire")] Nh,
        [Description("New Jersey")] Nj,
        [Description("New Mexico")] Nm,
        [Description("Nevada")] Nv,
        [Description("New York")] Ny,
        [Description("Oklahoma")] Ok,
        [Description("Ohio")] Oh,
        [Description("Oregon")] Or,
        [Description("Pennsylvania")] Pa,
        [Description("Rhode Island")] Ri,
        [Description("South Carolina")] Sc,
        [Description("South Dakota")] Sd,
        [Description("Tennessee")] Tn,
        [Description("Texas")] Tx,
        [Description("Utah")] Ut,
        [Description("Virginia")] Va,
        [Description("Vermont")] Vt,
        [Description("Washington")] Wa,
        [Description("Wisconsin")] Wi,
        [Description("West Virginia")] Wv,
        [Description("Wyoming")] Wy
    }
}